$(function(){$('input, textarea').placeholder();});$(document).ready(function(){$('#submit').click(function(){$.post("necesito_nana.php",$("#trabajo").serialize(),function(response){$('#success').html(response);});return false;});$('#submit2').click(function(){$.post("necesito_pega.php",$("#nana").serialize(),function(response){$('#success2').html(response);});return false;});$('#submit3').click(function(){$.post("contacto.php",$("#contacto").serialize(),function(response){$('#success3').html(response);});return false;});});$(document).ready(function(){$('a[href^="#"]').on('click',function(e){e.preventDefault();var target=this.hash,$target=$(target);$('html, body').stop().animate({'scrollTop':$target.offset().top},900,'swing',function(){window.location.hash=target;});});});function tooltipInit(){jQuery("[data-toggle='tooltip']").tooltip();}
function portfolioSort(){var p=jQuery('#portfolio1');var f=jQuery('.filterPortfolio');var data=p.clone();f.find('a').click(function(){var link=jQuery(this);var li=link.parents('li');if(li.hasClass('active')){return false;}
f.find('li').removeClass('active');li.addClass('active');var filtered=li.data('filter')?data.find('li[data-filter~="'+li.data('filter')+'"]'):data.find('li');p.quicksand(filtered,{duration:800,adjustHeight:false,easing:'easeInOutQuad'},function(){overlayContent('reload');});return false;});}
function accordionActive(){jQuery(".accordion").on("show",function(e){jQuery(e.target).prev(".accordion-heading").find(".accordion-toggle").addClass("active");}).on("hide",function(e){jQuery(this).find(".accordion-toggle").not(jQuery(e.target)).removeClass("active");}).each(function(){var $a=jQuery(this);$a.find("a.accordion-toggle").attr("data-parent","#"+$a.attr("id"));});}
function fadeFlexsliderInit(){jQuery('.flexslider.fadeFlex').flexslider({animation:'fade',animationLoop:false,slideshow:true,controlNav:false,directionNav:true,smoothHeight:true});}
function carouselFlexsliderInit(){jQuery('.flexslider.flexCarousel').flexslider({animation:"slide",animationLoop:true,itemWidth:140,minItems:2,maxItems:6,move:0,controlNav:false,directionNav:true});}
function overlayContent(i){if(i=='init'){jQuery('.contentoverlay').contenthover({overlay_opacity:0.6,effect:'fade',fade_speed:400,slide_speed:400,slide_direction:'bottom'});}
if(i=='reload'){jQuery('.ch_element').remove();jQuery('.contentoverlay').show();overlayContent('init');}}
function mainsliderInit(){jQuery('.flexslider.navmainslider').flexslider({animation:"slide",controlNav:false,directionNav:false,animationLoop:true,slideshow:false,itemWidth:320,itemMargin:0,minItems:2,maxItems:2,useCSS:false,asNavFor:".flexslider.mainslider"});jQuery('.flexslider.mainslider').flexslider({animation:"slide",controlNav:true,animationLoop:false,useCSS:false,slideshow:false,sync:".flexslider.navmainslider",start:function(){var $mele=jQuery(".flexslider.mainslider .flex-control-nav li").size();var $marginmele=400-$mele*14;jQuery('.flexslider.mainslider .flex-direction-nav .flex-prev').css('margin-left',$marginmele);jQuery('.flexslider.mainslider .flex-control-nav').css('margin-left',$marginmele+33);jQuery(".flexslider.mainslider .flex-control-nav, .flexslider.mainslider .flex-direction-nav .flex-prev, .flexslider.mainslider .flex-direction-nav .flex-next").fadeIn();}});}
jQuery(document).ready(function(){overlayContent('init');accordionActive();portfolioSort();tooltipInit();});jQuery(window).resize(function(){overlayContent('reload');});jQuery(window).load(function(){fadeFlexsliderInit();carouselFlexsliderInit();mainsliderInit();});